config/routes.rb
Rails.application.routes.draw do
  root to: "links#index"
  resources :links
  get '/:slug', to: 'links#show', as: :short
  delete 'links/:id', to: 'links#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
class Link < ApplicationRecord
  validates_presence_of :url
  validates :url, format: URI::regexp(%w[http https])
  validates_uniqueness_of :slug
  validates_length_of :url, within: 3..255, on: :create, message: "too long"
  validates_length_of :slug, within: 3..255, on: :create, message: "too long"

  before_validation :generate_slug

  def generate_slug
    self.slug = SecureRandom.uuid[0..4] if self.slug.nil? ||self.slug.empty?
    true
  end

  def short
    Rails.application.routes.url_helpers.short_url(slug: self.slug)
  end

  def self.shorten(url, slug = '')
    link = Link.where(url: url, slug: slug).first
    return link.short if link

    link = Link.new(url: url, slug: slug)
    return link.short if link.save

    Link.shorten(url, slug + SecureRandom.uuid[0..2])
  end

end

app/models/user.rb
class User < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
    before_action :set_link, only: [:show]

  # GET /links or /links.json
  def index
    @links = Link.all
    @links_count = Link.count
  end

  # GET /links/1 or /links/1.json
  def show
    if params[:slug]
      @link = Link.find_by(slug: params[:slug])
      @link.clicked += 1
      @link.save
      redirect_to @link.url, allow_other_host: true
    else
      @link = Link.find(params[:id])
    end
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # POST /links or /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save

        format.html { redirect_to links_path, notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1 or /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to link_url(@link), notice: "Link was successfully updated." }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1 or /links/1.json
  def destroy
    # @link.destroy
    @link = Link.find(params[:id])
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: "Link was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find_by(slug: params[:slug])
    end

    # Only allow a list of trusted parameters through.
    def link_params
      params.require(:link).permit(:url, :slug, :clicked)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title LinkShortener
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    %link{:crossorigin => "anonymous", :href => "https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css", :integrity => "sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N", :rel => "stylesheet"}/
    %script{:crossorigin => "anonymous", :integrity => "sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj", :src => "https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct", :src => "https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"}
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    = yield

app/views/links/_form.html.haml
= form_with(model: link) do |form|
  - if link.errors.any?
    %div{:style => "color: red"}
      %h2
        = pluralize(link.errors.count, "error")
        prohibited this link from being saved:
      %ul
        - link.errors.each do |error|
          %li= error.full_message
  %div
    = form.label :url, style: "display: block"
    = form.text_field :url
  %div
    = form.submit

app/views/links/_link.html.haml
%div{id: "#{dom_id link}"}
  %p
    %strong Url:
    = link.url
  %p
    %strong Shorten:
    = link_to short_url(link.slug), short_path(link.slug), method: :get
    %button{onclick: "copyText('#{short_url(link.slug)}')"}
      %i.fa-solid.fa-copy
  %img{src: RQRCode::QRCode.new(short_url(link.slug)).as_png(bit_depth: 1, cborder_modules: 4, color_mode: ChunkyPNG::COLOR_GRAYSCALE, color: 'black', file: nil, fill: 'white', module_px_size: 4, resize_exactly_to: false, resize_gte_to: false, size: 100).to_data_url}/
  %p
    %strong Clicked:
    = link.clicked

:javascript
  function copyText(data) {
    navigator.clipboard.writeText(data);
  }

app/views/links/edit.html.haml
%h1 Editing link
= render "form", link: @link
%br/
%div
  = link_to "Show this link", short_path
  |
  = link_to "Back to links", links_path

app/views/links/index.html.haml
%p{:style => "color: green"}= notice
%h1 Links
%br/
%br/
= bar_chart Link.group(:slug).sum(:clicked), height: "200px", width: "800px"
%br/
= area_chart Link.group(:slug).group_by_hour_of_day(:created_at).sum(:clicked), xtitle: "Hour of day", ytitle: "Clicked", height: "500px", width: "800px"
%br/
= pie_chart Link.group(:slug).sum(:clicked)
%br/
#links
  - @links.each do |link|
    = render link
    %p
      = button_to link_path(link.id), method: :get do
        %i.fa-solid.fa-chart-line
      = button_to link_path(link.id), method: :delete do
        %i.fa-solid.fa-trash-can
= button_to new_link_path, method: :get do
  %i.fa-solid.fa-plus

app/views/links/new.html.haml
%div
  = link_to links_path do
    %i.fa-solid.fa-arrow-left-long
= render "form", link: @link

app/views/links/show.html.haml
%p{style: "color: green"}= notice

.links-back
= link_to links_path, class: "fa fa-sharp fa-solid fa-left-long"

= render @link

.delete-link
= link_to link_path(@link), method: :delete, class: "fa fa-solid fa-trash-can"